### ISSUE TITLE
개발 편의성을 위한 ShortenUUID Generator 구현

### ISSUE THREAD

**Issue by re-mora** [baedal-legend/foody#103]
# 개요
개발 편의성을 위해 PK로 사용하고 있는 32자리의 UUID 중 time-low에 해당하는 8자리만 반환하는 ShortenUUIDGenerator를 구현합니다.

#  TODO
- [ ] JPA의 IdentifierGenerator를 구현한 Custom Generator 구현
  - [ ] Java의 UUID를 이용하여 생성된 32자리의 UUID 중 time-low에 해당하는 8자리만 반환하는 ShortenUUIDGenerator 구현
- [ ] @GeneratedValue와 @GenericGenerator를 이용한 Custom Generator 적용

# 참고 URL
[Toss Payments:UUID](https://docs.tosspayments.com/resources/glossary/uuid)
![Image](https://github.com/user-attachments/assets/74cdb8f4-c3b6-4225-b998-061310f5b5d5)
