### ISSUE TITLE
회원 가입 API

### ISSUE THREAD

**Issue by re-mora** [baedal-legend/foody#12]
# 개요
- 서비스 사용에 필요한 회원가입 기능을 구현합니다.
- 회원은 아래 기준에 따라 세 계층으로 분류 합니다.
  - 배달 서비스를 이용하는 고객
  - 상품을 등록하고 관리하는 가게 주인
  - 서비스를 관리하는 관리자
- Spring Security를 이용하여 각 회원 별 인증/인가 정책을 설정합니다.

# TODO
- [x] Spring Security 의존성 추가
- [x] Spring Security Configuration 생성 및 기본 정책 설정
  - [x] csrf, formLogin, httpBasic 설정 disable
  - [x] 회원 가입 요청 허용 정책 설정
  - [x] 비밀번호 암호화를 위한 PasswordEncoder Bean 등록
- [x] 회원 가입 API 구현
  - [x] 이메일 중복 검사
  - [x] 닉네임 중복 검사
  - [x] 비밀 번호 암호화 처리 (BCrypt)
  - [ ] 회원 저장
