### ISSUE TITLE
Local 환경의 postgreSQL 실행을 위한 환경 설정 구성

### ISSUE THREAD

**Issue by re-mora** [baedal-legend/foody#22]
# 개요
local 환경에서 일관된 실행 환경 및 개발 편의성을 위해 docker compose를 이용한 postgreSQL 실행 환경을 구성합니다.

# TODO
- [ ] postgreSQL docker-compose.yml 작성
- [ ] postgreSQL 실행에 필요한 환경 설정 분리 : .env
- [ ] gitignore에 volume 및 .env 추가
