### ISSUE TITLE
로그인 API

### ISSUE THREAD

**Issue by re-mora** [baedal-legend/foody#33]
# 개요 
사용자로부터 로그인 정보를 입력 받아 해당 회원에 대한 검증을 진행하고, 검증이 완료된 회원을 대상으로 JWT를 발행합니다.

# TODO
- [ ] jjwt 의존성 추가
- [ ] JWT 발급
- [ ] 로그인 API 구현
  - [ ] 회원 가입 여부 검증
  - [ ] 비밀번호 일치 여부 검증
  - [ ] access token 발급
    - [ ] access token 정책 정의 : 만료 시간
    - [ ] JWT 발급에 필요한 인증 정보 객체 정의 : Principal
    - [ ] JWT 발급에 필요한 환경 설정 구성
      - [ ] 발급 주체
      - [ ] 발급 대상
- [ ] 로그인 요청 허용 정책 설정
