### ISSUE TITLE
메뉴 등록 API 구현 

### ISSUE THREAD

**Issue by uzjaee** [baedal-legend/foody#39]
## 개요 ## 

메뉴 등록 API를 구현합니다. 
![Image](https://github.com/user-attachments/assets/20e9aaad-862b-42ff-a8f1-5a012130b80a)
## Todo ##
- [x] 가게 , 메뉴 연관관계 설정  
- [x]  isPublic 컬럼 추가
- [x] 메뉴 등록 API 구현 
- [x] 테스트 구현

### request ### 
```json

POST /menu
Content-Type: application/json
{
  "name": "김밥 라면 세트",
  "price": 6000,
  "description":"김밥과 라면을 같이 먹을 때 느끼는 행복을 느껴보세요",
  "menuStatus":"ON_SALE"
}


```

### response ### 

```json 
HTTP 201 Created
Location: /shop/1
```
