### ISSUE TITLE
파라미터가 바인딩된 실행 쿼리 출력을 위한 p6spy 설정

### ISSUE THREAD

**Issue by re-mora** [baedal-legend/foody#40]
# 개요 
test, local profile에서 파라미터가 바인딩된 쿼리 파라미터 출력을 위해 p6spy 의존성을 추가하고 환경 설정을 구성합니다.

# TODO
- [x] p6spy 의존성 추가
- [x] p6spy 쿼리 파라미터 출력 환경 설정 구성
- [x] profiles 별 p6spy 쿼리 출력 설정 적용
