### ISSUE TITLE
예외 처리를 위한 Global Exception Handler 및 오류 응답 객체 정의

### ISSUE THREAD

**Issue by re-mora** [baedal-legend/foody#43]
# 개요
비지니스 로직 구현 중 발생할 수 있는 예외 상황을 RuntimeException, IllegalArgumentException 등의 포괄적인 예외가 아닌 해당 도메인의 예외 상황을 보다 상세히 표현할 수 있는 Custom Exception과 Custom Error Code를 정의하고, 각 도메인에서 Throw된 Custom Exception Event를 수신하여 오류 응답, 로깅, 알림 등의 일괄적인 처리를 위한 단일 예외 처리부를 구현합니다.

#  TODO
- [ ] JSR 303, 380 Annotation 등의 표준 규격을 검증하는 Spring validation 의존성 추가
- [ ] Spring validation의 유효성 검증 결과 반환되는 ErrorFields 정보로부터 Client에게 오류 응답을 반환하기 위한 Custom ErrorResponse 정의
- [ ] 단일 예외 처리 GlobalExceptionHandler 정의
- [ ] CustomException 및 Expected, Unexpected Exception Handler 구현
