### ISSUE TITLE
가게 전체 조회 API 구현

### ISSUE THREAD

**Issue by eggnee** [baedal-legend/foody#48]
# 개요
가게 전체 조회 API를 구현합니다.

# TODO
- [x] 가게 전체 조회에 필요한 Repo, Service, Controller 구현
- [x] isPublic 필드값이 true인 가게들만 조회 (고객, 가게 주인, 관리자 모두) 
- [x] 영업중, 브레이크타임, 영업종료 순으로 조회
- [ ] 무슨 기준으로 정렬할 것인지 생각 - 리뷰
- [x] 어떤 정보들을 보일 것인지
- [x] 페이징 처리 필요

## Request
```
GET http://localhost:8080/shop?page=0&size=2
```
## Response
```json
{
  "content": [
    {
      "id": "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d",
      "name": "ddd",
      "description": "ddd",
      "status": "영업 중"
    },
    {
      "id": "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3acb4d",
      "name": "bbb",
      "description": "ddd",
      "status": "재료 준비 시간"
    }
  ],
  "pageable": {
    "pageNumber": 0,
    "pageSize": 2,
    "sort": {
      "empty": true,
      "sorted": false,
      "unsorted": true
    },
    "offset": 0,
    "paged": true,
    "unpaged": false
  },
  "last": true,
  "totalPages": 1,
  "totalElements": 2,
  "size": 2,
  "number": 0,
  "sort": {
    "empty": true,
    "sorted": false,
    "unsorted": true
  },
  "first": true,
  "numberOfElements": 2,
  "empty": false
}
```
