### ISSUE TITLE
가게 검색 API 구현

### ISSUE THREAD

**Issue by eggnee** [baedal-legend/foody#66]
# 개요
가게 검색 API를 구현합니다.

# TODO
- [x] 가게 검색에 필요한 Repo, Service, Controller 구현
- [x] isPublic이 true인 가게 메뉴들만 조회
- [x] 가게 이름 / 가게 메뉴로 키워드 검색하여 조회

## Request
```
GET http://localhost:8080/shop?keyworkd=
```
## Response
```json
{
  "content": [
    {
      "id": "2121e39b-1a88-43e0-b959-a4f649433bc5",
      "name": "마시도니",
      "description": "맛있는 제주흑돼지를 파는 마시도니입니다.",
      "status": "영업 종료",
      "menuNames": []
    }
  ],
  "pageable": {
    "pageNumber": 0,
    "pageSize": 1,
    "sort": {
      "empty": true,
      "sorted": false,
      "unsorted": true
    },
    "offset": 0,
    "paged": true,
    "unpaged": false
  },
  "last": true,
  "totalPages": 1,
  "totalElements": 1,
  "size": 1,
  "number": 0,
  "sort": {
    "empty": true,
    "sorted": false,
    "unsorted": true
  },
  "first": true,
  "numberOfElements": 1,
  "empty": false
}
```
