### ISSUE TITLE
회원 탈퇴 API

### ISSUE THREAD

**Issue by re-mora** [baedal-legend/foody#72]
# 개요
회원 탈퇴에 대한 API를 구현합니다. 회원 삭제 시 CommonAuditFields의 isDeleted 항목을 이용하여 soft-delete 처리 합니다. @SQLRestriction("is_deleted = false")를 이용하여 User Entity 조회 시 삭제된 Entity는 제외하도록 기본 조회 정책을 설정 합니다.

# TODO
- [ ] 회원 soft-delete 도메인 로직 구현
- [ ] 회원 삭제 Service 구현
- [ ] 회원 탈퇴 API 구현
