### ISSUE TITLE
Github Actions을 이용한 CI/CD 구성

### ISSUE THREAD

**Issue by re-mora** [baedal-legend/foody#83]
# 개요
Github actions 을 이용한  CI/CD를 위한 task를 구성합니다.

# TODO
- [ ] jib build task
- [ ] upload to ecr task
- [ ] deploy to EC2 (docker-compose)
