### ISSUE TITLE
메뉴 단일 조회 API 구현

### ISSUE THREAD

**Issue by uzjaee** [baedal-legend/foody#92]
## 개요 
메뉴 단일 상품을 조회하는 API를 제작합니다 .
메뉴 단일 상품을 테스트 할 수 있는 http client 코드를 작성합니다 .

## todo
- [x] 컨트롤러 코드 작성
- [x] 서비스 코드 작성
- [x] 데이터베이스 쿼리 구현
- [x] 테스트 코드 작성 
### Request 
```
GET  /menus/menu/{menuId} 
```
### Response
```
    {
        "id": "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d",
        "name": "김밥 라면세트 ",
        "price" : 7000,
        "description": "맛있는 김밥과 라면을 세트로 먹어보아요",
        "status": "판매중"
  }
```
